common: 
  # identity: 
  light-kdf: false
  # datadir: 
  overwrite-genesis: false
  start-block-num: 0
  # keystore: 
  syncmode: full
  garbage-collection-mode: full
  sender-tx-hash-indexing: false
  target-gas-limit: 4712388
  block-extra-data: 
  srvtype: fasthttp
  # rewardbase: 0
  write-address: false
  child-chain-indexing: false
  kes-nodetype-service: false
  ntp: 
    disable: false
    server: "pool.ntp.org:123"
  # authorized-nodes: 
  # gen-key-path: 
  # scsigner: 

txresend: 
  interval: 4
  max-count: 1000
  use-legacy: false

p2p: 
  cypress: false
  baobab: false
  network-id: 8217
  bootnodes: ""
  rw-timer-wait-time: 15s
  rw-timer-interval: 1000
  port: 32323
  sub-port: 32324
  multi-channel: false
  max-connections: 10
  max-request-content-length: 524288
  max-pend-peers: 0
  bn-addr: ":32323"
  nat: any
  no-discover: false
  net-restrict: 
  node-key: 
  node-key-hex: 

experimental:
  opcode-computation-cost-limit: 100000000
  block-generation-interval: 1
  block-generation-time-limit: 250ms

account-update:
  unlock: ""
  password: ""

vm: 
  debug: false
  log: 0
  internaltx: false

metrics-collection-reporting: 
  enable: false
  prometheus: false
  prometheus-port: 61001

autorestart: 
  enable: false
  timeout: 15m0s
  daemon-path: ~/klaytn/bin/kcnd

api:
  filter:
    getLogs: 
      maxitems: 10000
      deadline: 10s

db: 
  type: "levelDB"
  single: false
  num-statetrie-shards: 4
  no-perf-metrics: false
  no-parallel-write: false
  leveldb:
    compression: 0
    no-buffer-pool: false
    cache-size: 768
  dynamo: 
    table-name: ""
    region: ap-northeast-2
    is-provisioned: false
    read-capacity: 10000
    write-capacity: 10000
    read-only: false

snapshot-database: 
  enable: false
  cache-size: 512
  async-gen: true

state: 
  cache-size: 512
  block-interval: 128
  tries-in-memory: 128
  trie-cache-limit: -1
  trie-cache-save-period: 0s

cache: 
  type: 2
  scale: 0
  level: 
  memory: 0
  
statedb: 
  cache: 
    type: LocalCache
    num-fetcher-prefetch-worker: 32
    use-snapshot-for-prefetch: false
    redis: 
      endpoints: []
      cluster: false
      publish: false
      subscribe: false

servicechain:
  mainbridge: false
  mainbridge-port: 50505
  subbridge: false
  subbridge-port: 50506
  parent-chainid: 8217
  chain-tx-period: 1
  chain-tx-limit: 100
  vt-recovery: false
  vt-recovery-interval: 5
  new-account: false
  anchoring: false
  parent-operator-gaslimit: 10000000
  child-operator-gaslimit: 10000000
  consensus: istanbul

txpool: 
  nolocals: false
  allow-local-anchortx: false
  deny-remote-tx: false
  journal: transactions.rlp
  journal-interval: 1h0m0s
  price-limit: 1
  price-bump: 10
  exec-slots: 
    account: 16
    all: 4096
  nonexec-slots: 
    account: 64
    all: 1024
  lifetime: 5m0s
  keeplocals: false
  spamthrottler: 
    disable: false

http-rpc: 
  enable: false
  addr: localhost
  port: 8551
  api: ""
  gascap: 0
  eth-tx-feecap: 0
  read-timeout: 30
  write-timeout: 30
  idle-timeout: 120
  execution-timeout: 30
  concurrency-limit: 3000
  # cors-domain: ""
  vhosts: localhost
  eth-noncompatible: false

ws-rpc: 
  enable: false
  addr: localhost
  port: 8552
  api: ""
  origins: ""
  max-subscription-per-conn: 3000
  read-deadline: 0
  write-deadline: 0
  max-connections: 3000

g-rpc: 
  enable: false
  addr: localhost
  port: 8553

ipc: 
  disable: false
  path: ""

console:
  js-path: .
  # exec: 
  # preload: 

debug-profile: 
  verbosity: 3
  vmodule: ""
  backtrace: ""
  print-site: false
  pprof: 
    enable: false
    addr: 127.0.0.1
    port: 6060
  mem-profile: 
    file-name: ""
    rate: 524288
  block-profile: 
    rate: 0
  cpu-profile: 
    file-name: ""
  trace: 
    file-name: ""

db-syncer: 
  enable: false
  log-mode: false
  mode: multi
  genquery.th: 50
  insert-thread: 30
  bulk-size: 20 
  event-mode: head
  block-channel-size: 5
  max-block-diff: 0
  db: 
    host: ""
    port: 3306
    name: ""
    user: ""
    password: 
    max-idle: 50
    max-open: 30
    max-lifetime: 3600000000000 #ms

chain-data-fetcher: 
  enable: false
  mode: kafka
  no-default: false
  num-handlers: 10
  job-channel-size: 50
  block-channel-size: 50
  max-processing-data-size: 500
  kafka: 
    replicas: 1
    brokers: []
    partitions: 1
    topic: 
      resource: en-0
      environment: local
    max-message-bytes: 1000000
    segment-size: 1000000
    required-acks: 1
    msg-version: 1.0
    # producer-id: 
