// Copyright 2023 The klaytn Authors
// This file is part of the klaytn library.
//
// The klaytn library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// The klaytn library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with the klaytn library. If not, see <http://www.gnu.org/licenses/>.

package system

import (
	"errors"

	"github.com/klaytn/klaytn/common"
	"github.com/klaytn/klaytn/common/hexutil"
	"github.com/klaytn/klaytn/contracts/system_contracts"
	"github.com/klaytn/klaytn/log"
)

var (
	logger = log.NewModuleLogger(log.Blockchain)

	// Some system contracts are allocated at special addresses.
	CreditAddr      = common.HexToAddress("0x0000000000000000000000000000000000000000")
	AddressBookAddr = common.HexToAddress("0x0000000000000000000000000000000000000400")

	// System contract binaries to be injected at hardfork or used in testing.
	Kip103Code     = hexutil.MustDecode("0x" + system_contracts.TreasuryRebalanceBinRuntime)
	Kip103MockCode = hexutil.MustDecode("0x" + system_contracts.TreasuryRebalanceMockBinRuntime)

	// Errors during system contract interaction
	ErrKip103IncorrectBlock   = errors.New("incorrect rebalance block number")
	ErrKip103NotEnoughBalance = errors.New("the sum of source balances are less than the sum of destination balances")
	ErrKip103BadStatus        = errors.New("KIP103 contract is not in proper status")
)

// Solidity enums are not generated by abigen. Add them manually.
const (
	EnumKip103Status_Initialized uint8 = iota
	EnumKip103Status_Registered
	EnumKip103Status_Approved
	EnumKip103Status_Finalized
)
