= KIP 37

[.readme-notice]
NOTE: More documentation at http://kips.klaytn.com/KIPs/kip-37

This set of interfaces and contracts are all related to the http://kips.klaytn.com/KIPs/kip-37[KIP37 Multi Token Standard].

The KIP specifies seven interfaces:

* {IKIP37}: Core functionality required in all compliant implementation.
* {IKIP37Receiver}: One of two interfaces that must be implemented by contracts if they want to accept tokens through `safeTransferFrom`. Renamed from IKIP37TokenReceiver
* {IERC1155Receiver}: The second of two interfaces that must be implemented by contracts if they want to accept tokens through `safeTransferFrom`. Renamed from IERC1155TokenReceiver
* {IKIP37MetadataURI}: Optional extension that adds name, symbol, and token URI, almost always included. Renamed from IKIP37Metadata
* {IKIP37Mintable}: Optional extension that allows creation of token type and minting of those types.
* {IKIP37Burnable}: Optional extension that allows owners (or approved accounts) to burn tokens
* {IKIP37Pausable}: Optional extension that allows contract wide (and token type specific) pausing of transfering, minting, and burning


NOTE: This core set of contracts is designed to be unopinionated, allowing developers to access the internal functions in ERC1155 (such as <<ERC1155-_mint-address-uint256-uint256-bytes-,`_mint`>>) and expose them as external functions in the way they prefer. On the other hand, xref:ROOT:erc1155.adoc#Presets[ERC1155 Presets] (such as {ERC1155PresetMinterPauser}) are designed using opinionated patterns to provide developers with ready to use, deployable contracts.

== Core

{{IERCKIP37}}

{{IKIP37MetadataURI}}

{{KIP37}}

{{IKIP37Receiver}}

== Extensions

{{KIP37Pausable}}

{{KIP37Mintable}}

{{KIP37Burnable}}

{{KIP37Supply}}

{{KIP37URIStorage}}

== Presets

These contracts are preconfigured combinations of the above features. They can be used through inheritance or as models to copy and paste their source code.

{{KIP37PresetMinterPauser}}

== Utilities

{{ERC1155Holder}}
