= KIP 17

[.readme-notice]
NOTE: More documentation at https://kips.klaytn.com/KIPs/kip-17

This set of interfaces, contracts, and utilities are all related to the https://kips.klaytn.com/KIPs/kip-17[KIP17 Non-Fungible Token Standard].

The KIP specifies nine interfaces:

* {IKIP17}: Core functionality required in all compliant implementation.
* {IKIP17Receiver}: One of two interfaces that must be implemented by contracts if they want to accept tokens through `safeTransferFrom`. Renamed from IKIP17TokenReceived
* {IERC721Receiver}: The second of two interfaces that must be implemented by contracts if they want to accept tokens through `safeTransferFrom`. Renamed from IERC721TokenReceived
* {IKIP17Metadata}: Optional extension that adds name, symbol, and token URI, almost always included.
* {IKIP17Enumerable}: Optional extension that allows enumerating the tokens on chain, often not included since it requires large gas overhead.
* {IKIP17Mintable}: Optional extension that allows permissioned minting of tokens (without a tokenURI)
* {IKIP17MetadataMintable}: Optional extension that allows permissioned minting of tokens (with a tokenURI)
* {IKIP17Burnable}: Optional extension that allows owners (or approved accounts) to burn tokens
* {IKIP17Pausable}: Optional extension that allows permissioned contract wide pausing of transfering, minting, and burning. Note: removed Paused and UnPaused events. This is consistent with the IKIP37Pausable implementation, and also with the Pausable.sol OpenZeppelin implementation.

Klaytn Contract Library provides implementations of all nine interfaces:

* {KIP17}: The core and metadata extensions, with a base URI mechanism.
* {KIP17Holder}: A bare bones implementation of the receiver interface (only KIP17 tokens).
* {KIP17ERC721Holder}: A bare bones implementation of the receiver interface (to receive either KIP17 or ERC721 tokens).
* {KIP17Enumerable}: The enumerable extension.
* {KIP17Mintable}: The mintable extension.
* {KIP17MetadataMintable}: The mintable with URI extension.
* {KIP17Burnable}: A way for token holders to burn their own tokens.
* {KIP17Pausable}: A primitive to pause contract operation.

Additionally there are a few of other extensions:

* {KIP17URIStorage}: A more flexible but more expensive way of storing metadata.
* {KIP17Votes}: Support for voting and vote delegation.
* {KIP17Royalty}: A way to signal royalty information following the Ethereum ERC2981 standard.

NOTE: This core set of contracts is designed to be unopinionated, allowing developers to access the internal functions in KIP17 (such as <<KIP17-_mint-address-uint256-,`_mint`>>) and expose them as external functions in the way they prefer. On the other hand, xref:ROOT:erc721.adoc#Presets[KIP17 Presets] (such as {KIP17PresetMinterPauserAutoId}) are designed using opinionated patterns to provide developers with ready to use, deployable contracts.

== Core

{{IKIP17}}

{{IKIP17Metadata}}

{{IKIP17Enumerable}}

{{KIP17}}

{{KIP17Enumerable}}

{{IKIP17Receiver}}

== Extensions

{{KIP17Mintable}}

{{KIP17MetadataMintable}}

{{KIP17Pausable}}

{{KIP17Burnable}}

{{KIP17URIStorage}}

{{KIP17Votes}}

{{KIP17Royalty}}

== Presets

These contracts are preconfigured combinations of the above features. They can be used through inheritance or as models to copy and paste their source code.

{{KIP17PresetMinterPauserAutoId}}

== Utilities

{{KIP17Holder}}

{{KIP17ERC721Holder}}
