// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package genesis

import (
	"encoding/json"
	"errors"
	"ground-x/go-gxplatform/common"
	"ground-x/go-gxplatform/common/hexutil"
	"ground-x/go-gxplatform/common/math"
	"ground-x/go-gxplatform/core"
	"math/big"
)

var _ = (*genesisSpecMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (b BFTGenesis) MarshalJSON() ([]byte, error) {
	type BFTGenesis struct {
		Config     *BFTChainConfig                                  `json:"config"`
		Nonce      math.HexOrDecimal64                              `json:"nonce"`
		Timestamp  math.HexOrDecimal64                              `json:"timestamp"`
		ExtraData  hexutil.Bytes                                    `json:"extraData"`
		GasLimit   math.HexOrDecimal64                              `json:"gasLimit"   gencodec:"required"`
		Difficulty *math.HexOrDecimal256                            `json:"difficulty" gencodec:"required"`
		Mixhash    common.Hash                                      `json:"mixHash"`
		Coinbase   common.Address                                   `json:"coinbase"`
		Alloc      map[common.UnprefixedAddress]core.GenesisAccount `json:"alloc"      gencodec:"required"`
		Number     math.HexOrDecimal64                              `json:"number"`
		GasUsed    math.HexOrDecimal64                              `json:"gasUsed"`
		ParentHash common.Hash                                      `json:"parentHash"`
	}
	var enc BFTGenesis
	enc.Config = b.Config
	enc.Nonce = math.HexOrDecimal64(b.Nonce)
	enc.Timestamp = math.HexOrDecimal64(b.Timestamp)
	enc.ExtraData = b.ExtraData
	enc.GasLimit = math.HexOrDecimal64(b.GasLimit)
	enc.Difficulty = (*math.HexOrDecimal256)(b.Difficulty)
	enc.Mixhash = b.Mixhash
	enc.Coinbase = b.Coinbase
	if b.Alloc != nil {
		enc.Alloc = make(map[common.UnprefixedAddress]core.GenesisAccount, len(b.Alloc))
		for k, v := range b.Alloc {
			enc.Alloc[common.UnprefixedAddress(k)] = v
		}
	}
	enc.Number = math.HexOrDecimal64(b.Number)
	enc.GasUsed = math.HexOrDecimal64(b.GasUsed)
	enc.ParentHash = b.ParentHash
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (b *BFTGenesis) UnmarshalJSON(input []byte) error {
	type BFTGenesis struct {
		Config     *BFTChainConfig                                  `json:"config"`
		Nonce      *math.HexOrDecimal64                             `json:"nonce"`
		Timestamp  *math.HexOrDecimal64                             `json:"timestamp"`
		ExtraData  *hexutil.Bytes                                   `json:"extraData"`
		GasLimit   *math.HexOrDecimal64                             `json:"gasLimit"   gencodec:"required"`
		Difficulty *math.HexOrDecimal256                            `json:"difficulty" gencodec:"required"`
		Mixhash    *common.Hash                                     `json:"mixHash"`
		Coinbase   *common.Address                                  `json:"coinbase"`
		Alloc      map[common.UnprefixedAddress]core.GenesisAccount `json:"alloc"      gencodec:"required"`
		Number     *math.HexOrDecimal64                             `json:"number"`
		GasUsed    *math.HexOrDecimal64                             `json:"gasUsed"`
		ParentHash *common.Hash                                     `json:"parentHash"`
	}
	var dec BFTGenesis
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Config != nil {
		b.Config = dec.Config
	}
	if dec.Nonce != nil {
		b.Nonce = uint64(*dec.Nonce)
	}
	if dec.Timestamp != nil {
		b.Timestamp = uint64(*dec.Timestamp)
	}
	if dec.ExtraData != nil {
		b.ExtraData = *dec.ExtraData
	}
	if dec.GasLimit == nil {
		return errors.New("missing required field 'gasLimit' for BFTGenesis")
	}
	b.GasLimit = uint64(*dec.GasLimit)
	if dec.Difficulty == nil {
		return errors.New("missing required field 'difficulty' for BFTGenesis")
	}
	b.Difficulty = (*big.Int)(dec.Difficulty)
	if dec.Mixhash != nil {
		b.Mixhash = *dec.Mixhash
	}
	if dec.Coinbase != nil {
		b.Coinbase = *dec.Coinbase
	}
	if dec.Alloc == nil {
		return errors.New("missing required field 'alloc' for BFTGenesis")
	}
	b.Alloc = make(core.GenesisAlloc, len(dec.Alloc))
	for k, v := range dec.Alloc {
		b.Alloc[common.Address(k)] = v
	}
	if dec.Number != nil {
		b.Number = uint64(*dec.Number)
	}
	if dec.GasUsed != nil {
		b.GasUsed = uint64(*dec.GasUsed)
	}
	if dec.ParentHash != nil {
		b.ParentHash = *dec.ParentHash
	}
	return nil
}
